(function(a){a.fn.Weatherflat=function(b,c,e){var f={unit:"c",photo:false,image:true,country:false,highlow:true,wind:false,humidity:false,visibility:false,sunrise:false,sunset:false,forecast:true,showerror:true,linktarget:"_self",woeid:false};var c=a.extend(f,c);var g="odd";return this.each(function(p,t){var k=a(t);
if(!k.hasClass("Weatherflat")){k.addClass("Weatherflat");}if(!a.isArray(b)){return false;}var q=b.length;if(q>10){q=10;}var v="";for(var p=0;p<q;p++){if(v!=""){v+=",";}v+="'"+b[p]+"'";}now=new Date();var l=c.woeid?"woeid":"location";var u="select * from weather.forecast where "+l+" in ("+v+") and u='"+c.unit+"'";
var s="http://query.yahooapis.com/v1/public/yql?q="+encodeURIComponent(u)+"&rnd="+now.getFullYear()+now.getMonth()+now.getDay()+now.getHours()+"&format=json&callback=?";a.ajax({type:"GET",url:s,dataType:"json",success:function(z){if(z.query){if(z.query.results.channel.length>0){var x=z.query.results.channel.length;
for(var y=0;y<x;y++){j(t,z.query.results.channel[y],c);}}else{j(t,z.query.results.channel,c);}if(a.isFunction(e)){e.call(this,k);}}else{if(c.showerror){k.html("<p>Weather information unavailable</p>");}}},error:function(i){if(c.showerror){k.html("<p>Weather request failed</p>");}}});var j=function(D,F,G){var x=a(D);
if(F.description!="Yahoo! Weather Error"){var A=F.wind.direction;if(A>=348.75&&A<=360){A="北风";}if(A>=0&&A<11.25){A="北风";}if(A>=11.25&&A<33.75){A="北东北风";}if(A>=33.75&&A<56.25){A="东北风";}if(A>=56.25&&A<78.75){A="东东北风";}if(A>=78.75&&A<101.25){A="东风";}if(A>=101.25&&A<123.75){A="东东南风";}if(A>=123.75&&A<146.25){A="东南风";
}if(A>=146.25&&A<168.75){A="南东南风";}if(A>=168.75&&A<191.25){A="南风";}if(A>=191.25&&A<213.75){A="南西南风";}if(A>=213.75&&A<236.25){A="西南风";}if(A>=236.25&&A<258.75){A="西西南风";}if(A>=258.75&&A<281.25){A="西风";}if(A>=281.25&&A<303.75){A="西西北风";}if(A>=303.75&&A<326.25){A="西北风";}if(A>=326.25&&A<348.75){A="北西北风";}var y=F.item.forecast[0];
wpd=F.item.pubDate;n=wpd.indexOf(":");tpb=w(wpd.substr(n-2,8));tsr=w(F.astronomy.sunrise);tss=w(F.astronomy.sunset);if(tpb>tsr&&tpb<tss){daynight="day";}else{daynight="night";}if(G.photo){bgphoto='style="background: url(http://o.aolcdn.com/os/weather/backgrounds/bg-'+daynight+"-"+F.item.condition.code+'.jpg)"';
}else{bgphoto="";}var C='<div class="'+g+" "+daynight+'" '+bgphoto+">";C+='<div class="weatherfirst">';if(G.image){C+='<i class="icon-'+F.item.condition.code+'"></i>';}C+='<div class="details">';if(G.country){C+='<div class="weatherCountry">'+F.location.country+"</div>";}C+='<div class="weatherTemp">'+F.item.condition.temp+"&deg;</div>";
C+='<div class="weatherDesc">'+h(F.item.condition.text)+"</div>";console.info("first condition:"+F.item.condition.text);var z=F.item.forecast;if(G.highlow){C+='<div class="weatherRange">'+y.low+"&deg;~ "+y.high+"&deg;</div>";}if(G.wind){C+='<div class="weatherWind">风速: '+A+" "+F.wind.speed+F.units.speed+"</div>";
}if(G.humidity){C+='<div class="weatherHumidity">Humidity: '+F.atmosphere.humidity+"</div>";}if(G.visibility){C+='<div class="weatherVisibility">Visibility: '+F.atmosphere.visibility+"</div>";}if(G.sunrise){C+='<div class="weatherSunrise">Sunrise: '+F.astronomy.sunrise+"</div>";}if(G.sunset){C+='<div class="weatherSunset">Sunset: '+F.astronomy.sunset+"</div>";
}C+="</div></div>";if(G.forecast){C+='<div class="weatherForecast">';var E=F.item.forecast;for(var B=1;B<E.length;B++){C+='<div class="weatherForecastItem">';C+='<div class="weatherForecastDay">'+o(E[B].day)+"</div>";C+='<i class="icon-'+E[B].code+'"></i>';console.info(E[B].text);C+='<div class="weatherForecastText">'+h(E[B].text)+"</div>";
C+='<div class="weatherForecastRange"> '+E[B].low+"&deg"+" ~"+E[B].high+"&deg"+"</div>";C+="</div>";}C+="</div>";}}else{var C='<div class="weatherItem '+g+'">';C+='<div class="weatherError">City not found</div>';}C+="</div>";if(g=="odd"){g="even";}else{g="odd";}x.append(C);};var w=function(i){d=new Date();
r=new Date(d.toDateString()+" "+i);return r;};var m=function(i){var x=new Date(i);return x.getFullYear()+"年"+(x.getMonth()+1)+"月"+x.getDate()+"日";};var o=function(x){var z=enDate.split(",");var A=cnDate.split(",");for(var y=0;y<z.length;y++){if(z[y].toLowerCase()==x.toLowerCase()){return A[y];}}};var h=function(y){var A=enWeather.split(",");
var z=cnWeather.split(",");for(var x=0;x<A.length;x++){if(A[x].toLowerCase()==y.toLowerCase()){return z[x];}}return y;};});};})(jQuery);

