(function(a){jQuery.fn.flipCountDown=jQuery.fn.flipcountdown=function(b){var f={showHour:true,showMinute:true,showSecond:true,am:false,tzoneOffset:0,speedFlip:60,period:1000,tick:function(){return new Date();},autoUpdate:true,size:"md",beforeDateTime:false,prettyPrint:function(g){return(g instanceof Array)?g.join(" "):g;
}},e=66,d={lg:77,md:52,sm:35,xs:24},c=function(i){var l=a('<div class="xdsoft_flipcountdown"></div>'),q=a('<div class="xdsoft_clearex"></div>'),s=a.extend({},f),k=0,m=function(v,u,t){if(!isNaN(u)){p(v,u,((u>t&&!(u==9&&t==0))||(u==0&&t==9))?-1:1,!((u==9&&t==0)||(u==0&&t==9))?Math.abs(u-t):1);}else{v.css("background-position","0px -"+((t+1)*6*d[s.size]+1)+"px");
}},p=function(v,t,w,u){if(u<1){return;}j(v,-((t+1)*6*d[s.size]+1),1,w,function(){p(v,t+w,w,u-1);},u);},j=function(u,w,x,v,y,t){if(w<=-d[s.size]*e){w=-(6*d[s.size]+1);}u.css("background-position","0px "+w+"px");if(x<=6){setTimeout(function(){j(u,w-v*d[s.size],++x,v,y,t);},parseInt(s.speedFlip/t));}else{y();
}},h=[],o=function(u,t){return u&&t&&((u==t)||(/^[0-9]+$/.test(u+""+t))||(/^[:.\s]+$/.test(u+""+t)));},r=function(w){if(!(w instanceof Array)||!w.length){return false;}for(var u=0,y=w.length;u<y;u++){if(!h[u]){h[u]=a('<div class="xdsoft_digit"></div>');q.before(h[u]);}if(h[u].data("value")!=w[u]){if(!o(h[u].data("value"),w[u])){h[u].removeClass("xdsoft_separator").removeClass("xdsoft_dot");
switch(w[u]){case":":h[u].addClass("xdsoft_separator");break;case".":h[u].addClass("xdsoft_dot");break;case" ":h[u].addClass("xdsoft_space");break;}}if(!isNaN(w[u])){var t=parseInt(h[u].data("value")),v=parseInt(h[u].data("i")),x=parseInt(w[u]);m(h[u],t,x);}h[u].data("value",w[u]);h[u].data("i",u);}}if(h.length>w.length){for(;
u<h.length;u++){h[u][0].parentNode.removeChild(h[u][0]);delete h[u];}h.splice(w.length);}},g=0,n=function(){var v="1",u=[];if(s.tick){v=s.prettyPrint.call(i,(s.tick instanceof Function)?s.tick.call(i,g):s.tick);}if(typeof v!=="undefined"){switch(v.constructor){case Date:var t=(v.getHours()+s.tzoneOffset)%(s.am?12:24);
if(s.showHour){u.push(parseInt(t/10));u.push(t%10);}if(s.showHour&&(s.showMinute||s.showSecond)){u.push(":");}if(s.showMinute){u.push(parseInt(v.getMinutes()/10));u.push(v.getMinutes()%10);}if(s.showMinute&&s.showSecond){u.push(":");}if(s.showSecond){u.push(parseInt(v.getSeconds()/10));u.push(v.getSeconds()%10);
}break;case String:u=v.replace(/[^0-9\:\.\s]/g,"").split("");break;case Number:u=v.toString().split("");break;}r(u);}};l.append(q).on("xdinit.xdsoft",function(){clearInterval(k);if(s.autoUpdate){k=setInterval(n,s.period);}n();});i.data("setOptions",function(t){s=a.extend(true,{},s,t);if(!d[s.size]){s.size=defaulOptions.size;
}if(s.beforeDateTime&&!t.tick){if(typeof(s.beforeDateTime)=="string"){s.beforeDateTime=Math.round((new Date(s.beforeDateTime)).getTime()/1000);}else{if(Object.prototype.toString.call(s.beforeDateTime)!=="[object Date]"){s.beforeDateTime=Math.round((new Date()).getTime()/1000)+365*24*60;}}var u=function(v){return v>9?v:"0"+v;
};s.tick=function(){var x=Math.max(0,s.beforeDateTime-Math.round((new Date()).getTime()/1000)),v=86400,A=3600,B=parseInt(x/v),w=parseInt((x%v)/A),y=parseInt(((x%v)%A)/60),z=((x%v)%A)%60;return[u(B),u(w),u(y),u(z)];};}l.addClass("xdsoft_size_"+s.size).trigger("xdinit.xdsoft");});i.append(l);};return this.each(function(){var g=a(this);
if(!g.data("setOptions")){g.addClass("xdsoft");c(g);}g.data("setOptions")&&a.isFunction(g.data("setOptions"))&&g.data("setOptions")(b);});};})(jQuery);

